-- Stores unique state names where the wells are located.
--table states
CREATE TABLE states (
    state_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name VARCHAR2(50) UNIQUE NOT NULL
);

--********************************************************************************
--Links districts to their respective states using state_id
--table districts
CREATE TABLE districts (
    district_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id NUMBER REFERENCES states(state_id),
    district_name VARCHAR2(50) NOT NULL
);
--********************************************************************************
--Links tahsils to districts

CREATE TABLE tahsils (
    tahsil_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id NUMBER REFERENCES districts(district_id),
    tahsil_name VARCHAR2(50) NOT NULL
);

--********************************************************************************
--Links blocks to tahsils.
CREATE TABLE blocks (
    block_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahsil_id NUMBER REFERENCES tahsils(tahsil_id),
    block_name VARCHAR2(50) NOT NULL
);

--********************************************************************************
--This table contains the core information about the wells.
--Links each well to its location using state_id, district_id, tahsil_id, and block_id.
CREATE TABLE wells (
    site_id VARCHAR2(20) PRIMARY KEY,
    latitude VARCHAR2(20),
    longitude VARCHAR2(20),
    site_type VARCHAR2(50),
    site_sub_type VARCHAR2(50),
    state_id NUMBER REFERENCES states(state_id),
    district_id NUMBER REFERENCES districts(district_id),
    tahsil_id NUMBER REFERENCES tahsils(tahsil_id),
    block_id NUMBER REFERENCES blocks(block_id),
    site_name VARCHAR2(100),
    aquifer_type VARCHAR2(50),
    depth NUMBER(10, 2)
);
--********************************************************************************
--Create the Water Levels Table
--This table stores time-dependent water level data for each well.
--Links water level records to specific wells via site_id.
CREATE TABLE water_levels (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id VARCHAR2(20) REFERENCES wells(site_id),
    wls_date DATE NOT NULL,
    wls_wtr_level NUMBER(10, 2),
    wls_dry_well CHAR(1) CHECK (wls_dry_well IN ('Y', 'N'))
);
--********************************************************************************
--Insert Reference Data
--Populate states, districts, and other lookup tables with unique values from your dataset.
INSERT INTO states (state_name) VALUES ('Maharashtra');

INSERT INTO districts (state_id, district_name)
VALUES (
    (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
    'Ahmednagar'
);

INSERT INTO tahsils (district_id, tahsil_name)
VALUES (
    (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
    'Sangamner'
);

INSERT INTO blocks (tahsil_id, block_name)
VALUES (
    (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
    'Sangamner Block'
);


--wells in sangamner
INSERT INTO wells 
(site_id, latitude, longitude, site_type, site_sub_type, state_id, district_id, tahsil_id, block_id, site_name, aquifer_type, depth)
SELECT 'W192100074103001', '19°21''0" N', '74°10''30" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Ambikhalsa', 'Unconfined', 17 FROM dual

UNION ALL

SELECT 'W191640074134001', '19°16''40" N', '74°13''40" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Bote', 'Unconfined', 9 FROM dual

UNION ALL

SELECT 'W192900074120001', '19°29''0" N', '74°12''0" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Chandanapuri', 'Unconfined', 23 FROM dual

UNION ALL

SELECT 'W193530074180001', '19°35''30" N', '74°18''0" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Kokangaon', 'Unconfined', 15 FROM dual

UNION ALL

SELECT 'W193400074131501', '19°34''0" N', '74°13''15" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Sangamner', 'Unconfined', 15 FROM dual

UNION ALL

SELECT 'W193100074151001', '19°31''0" N', '74°15''10" E', 'Dug Well', NULL, 
       (SELECT state_id FROM states WHERE state_name = 'Maharashtra'),
       (SELECT district_id FROM districts WHERE district_name = 'Ahmednagar'),
       (SELECT tahsil_id FROM tahsils WHERE tahsil_name = 'Sangamner'),
       NULL, 'Tambhol', 'Unconfined', 20 FROM dual;

--water level data
INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W192100074103001', TO_DATE('30-NOV-21', 'DD-MON-YY'), 8.91, 'N');

INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W191640074134001', TO_DATE('30-NOV-21', 'DD-MON-YY'), 3.81, 'N');

INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W192900074120001', TO_DATE('30-NOV-21', 'DD-MON-YY'), 9.5, 'N');

INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W193530074180001', TO_DATE('30-NOV-21', 'DD-MON-YY'), 2.85, 'N');

INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W193400074131501', TO_DATE('30-NOV-21', 'DD-MON-YY'), 6.21, 'N');

INSERT INTO water_levels (site_id, wls_date, wls_wtr_level, wls_dry_well)
VALUES ('W193100074151001', TO_DATE('30-NOV-21', 'DD-MON-YY'), 4.81, 'N');



desc states;
desc districts;
desc tahsils;
desc blocks;
desc wells;
desc water_levels;

SELECT * FROM states;
SELECT * FROM districts;
SELECT * FROM tahsils;
SELECT * FROM blocks;
SELECT * FROM wells;
SELECT * FROM water_levels;


--plsql procedure if that i entered the site_name sangamner then it will give me water depth  in that area
CREATE OR REPLACE PROCEDURE get_water_depth_by_site (
    p_site_name IN VARCHAR2,   -- Input parameter for the site name
    p_water_depth OUT NUMBER   -- Output parameter for water depth
) IS
BEGIN
    -- Query to fetch water depth based on the site name
    SELECT wls_wtr_level
    INTO p_water_depth
    FROM water_levels
    WHERE site_id IN (
        SELECT site_id
        FROM wells
        WHERE site_name = p_site_name
    )
    AND ROWNUM = 1;  -- Ensure that only one result is returned (in case of multiple records)

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- If no data is found, return a message or null
        p_water_depth := NULL;
        DBMS_OUTPUT.PUT_LINE('No data found for site: ' || p_site_name);
    WHEN TOO_MANY_ROWS THEN
        -- If more than one record is returned, handle the error
        p_water_depth := NULL;
        DBMS_OUTPUT.PUT_LINE('Multiple records found for site: ' || p_site_name);
    WHEN OTHERS THEN
        -- For any other errors, print a message
        p_water_depth := NULL;
        DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
END get_water_depth_by_site;

---execution
SET SERVEROUTPUT ON 100000;
DECLARE
    v_water_depth NUMBER;  -- Variable to hold the output value
BEGIN
    -- Call the procedure with the site name 'Sangamner'
    get_water_depth_by_site('Sangamner', v_water_depth);

    -- Output the result
    DBMS_OUTPUT.PUT_LINE('Water Depth for Sangamner: ' || v_water_depth);
END;


